server:
  port: 8089

spring:
  profiles:
    active: dev
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/snake?useUnicode=true&characterEncoding=utf-8
  jackson:
    property-naming-strategy: SNAKE_CASE
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-wait: 30s
        min-idle: 10
        max-idle: 50
  mail:
    host: smtp.qq.com
    port: 587
    username: 1320524236@qq.com
    password: imjfxomxonmgjdhe

system:
  security:
    token-name: snake_token
  redis-key:
    token-key-prefix: 'token::'


mybatis-plus:
  type-aliases-package: com.fgj.comment.mybatisplus.entity,com.fgj.comment.domain.vo
  mapper-locations: classpath:mapper/*.xml
  type-handlers-package: com.fgj.comment.mybatisplus.handler
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    root: info
  file: E:/spring-boot-logs/comment/comment.log
